apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: tc_webapp
  template:
    metadata:
      labels:
        app: tc_webapp
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.image.containerName }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}